#!/bin/bash
#Usage ./scripts/change_branch branch_name

#git checkout ${1}
#git_repos="gcc binutils gdb glibc newlib qemu"
git_repos="gcc binutils gdb glibc"

cd gits
for x in ${git_repos}; do
cd $x;
  git checkout ${1}
cd ../
done
